### ISSUE TITLE
this isn't worth making a new release for but can we include the github release # in the readme also

### ISSUE THREAD

**Issue by aledj2** [moka-guys/dnanexus_vardict#2]

**Comment by woook** [comment]
Are you sure that’s ok if this is going to be used diagnostically?

**Comment by woook** [comment]
Are you sure it's ok to not do this if this release will be used diagnostically?

**Comment by aledj2** [comment]
The github release # is in the json and where it should be. just not in the readme. The release hasn't been done yet so would only take a second

**Comment by woook** [comment]
Let’s do it then.
